### ISSUE TITLE
Could you provide the link of pre-processed dataset?

### ISSUE THREAD

**Issue by zhangguanghui1** [ispc-lab/RSKDD-Net#1]
Thank you open you source code for the great work. Could you provide the download link of pre-processed dataset? My email is zhanggh1@mail.ustc.edu.cn Thank you very much.

**Comment by zhangguanghui1** [comment]
Hello, I know the leaf size is 0.1m in your paper, what is the parameter about search stage (see below) when solving the surface normal?

// Use all neighbors in a sphere of radius 3cm
 ne.setRadiusSearch (0.03);  # todo change

Thank you!

**Comment by FanLu97** [comment]
@zhangguanghui1 Thank you for your interest in our work! We will provide the code for data pre-processing soon.

**Comment by FanLu97** [comment]
@zhangguanghui1 The code for data preprocessing has been updated.
